"""LangGraph workflow definition for the privacy-preserving, stateful survey agent."""

from __future__ import annotations

import json
import os
from typing import Any, Callable, Literal

from langchain_core.messages import AIMessage, BaseMessage, SystemMessage, ToolMessage
from langgraph.graph import END, START, StateGraph

from src.router import route_decision, router_node
from src.state import AgentState
from src.tools import execute_safe_query, safe_query_tool

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

SYSTEM_PROMPT = """You are SurveyIQ, a senior privacy-first AI analyst querying the Pierce County WA Employee Engagement Survey dataset (2019–2024).

CORE DIRECTIVES & ARCHITECTURAL CONSTRAINTS:
1. Strict Aggregates Only: You can only query data via the `safe_query_tool`. Never attempt to guess, extract, or hallucinate raw individual rows.
2. Privacy Guardrail Awareness: The underlying query layer enforces k-anonymity (k >= 10). If a specific subgroup has fewer than 10 respondents, exact data is suppressed to prevent differencing attacks, and a generalized department aggregate is automatically returned. In your final answer, clearly disclose any privacy suppression and explain that the cohort was generalized for confidentiality.
3. Multi-Hop Comparative Capability: When asked a comparative question (e.g. comparing two departments, two roles, or wave-over-wave changes), you MUST execute separate, sequential query tool calls. Retain the context from your first query, execute the subsequent query, and then synthesize a quantitative comparative answer.
4. Quantitative Accuracy: Always report respondent counts (n), mean scores, and distribution counts accurately from the tool responses.
"""

LOOP_SAFETY_BUDGET = 4


def create_llm_node(llm: Any = None) -> Callable[[AgentState], dict[str, Any]]:
    """Creates the agent LLM node using Claude Sonnet 4.5 (or provided model)."""
    if llm is None:
        try:
            from langchain_anthropic import ChatAnthropic

            api_key = os.environ.get("ANTHROPIC_API_KEY")
            model_name = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5-20250929")
            if not api_key:
                # Fallback to local deterministic agent if key not present
                from src.mock_llm import DeterministicSurveyLLM

                llm = DeterministicSurveyLLM()
            else:
                llm = ChatAnthropic(
                    model=model_name,
                    temperature=0.0,
                    api_key=api_key,
                ).bind_tools([safe_query_tool])
        except Exception:
            from src.mock_llm import DeterministicSurveyLLM

            llm = DeterministicSurveyLLM()

    def agent_node(state: AgentState) -> dict[str, Any]:
        messages = list(state.get("messages", []))
        # Ensure system prompt is present
        if not messages or not isinstance(messages[0], SystemMessage):
            messages = [SystemMessage(content=SYSTEM_PROMPT)] + messages

        try:
            response = llm.invoke(messages)
        except Exception as e:
            # If the live model API call fails (e.g., 404 model not found, invalid key, rate limit),
            # gracefully fall back to the deterministic survey LLM
            print(f"[SurveyIQ Warning] Live LLM call failed ({e}). Falling back to deterministic agent.")
            from src.mock_llm import DeterministicSurveyLLM
            fallback_llm = DeterministicSurveyLLM()
            response = fallback_llm.invoke(messages)

        return {"messages": [response]}

    return agent_node


def tool_execution_node(state: AgentState) -> dict[str, Any]:
    """Executes tool calls generated by the LLM, increments step_count, and logs metadata."""
    messages = state.get("messages", [])
    last_message = messages[-1] if messages else None
    
    tool_messages: list[BaseMessage] = []
    metadata_events: list[dict[str, Any]] = []

    if last_message and hasattr(last_message, "tool_calls") and last_message.tool_calls:
        for call in last_message.tool_calls:
            tool_name = call.get("name")
            tool_args = call.get("args", {})
            call_id = call.get("id", "call_default")

            if tool_name in ("safe_query_tool", "execute_safe_query", "query_aggregate"):
                result = execute_safe_query(**tool_args)
                result_dict = result.to_dict()

                # Collect privacy and execution metadata
                if result.metadata_event:
                    metadata_events.append(result.metadata_event)

                metadata_events.append({
                    "type": "tool_execution",
                    "tool": tool_name,
                    "args": tool_args,
                    "respondent_count": result.respondent_count,
                    "status": result.status,
                })

                tool_messages.append(
                    ToolMessage(
                        content=json.dumps(result_dict),
                        tool_call_id=call_id,
                        name=tool_name,
                    )
                )

    current_step = state.get("step_count", 0)
    step_increment = len(tool_messages) if tool_messages else 1
    return {
        "messages": tool_messages,
        "step_count": current_step + step_increment,
        "metadata_log": metadata_events,
    }


def terminal_budget_node(state: AgentState) -> dict[str, Any]:
    """Terminal node reached when step_count >= 4."""
    error_msg = (
        "Terminal error: Operational budget is exhausted (step count >= 4). "
        "Execution halted to prevent runaway loops."
    )
    return {
        "messages": [AIMessage(content=error_msg)],
        "metadata_log": [
            {
                "type": "terminal_budget_exhausted",
                "step_count": state.get("step_count", 0),
                "error": error_msg,
            }
        ],
    }


def route_after_llm(state: AgentState) -> Literal["terminal_budget_node", "tool_node", "end"]:
    """Conditional edge evaluating loop safety budget and tool invocation."""
    step_count = state.get("step_count", 0)

    # 1. Enforce loop safety budget
    if step_count >= LOOP_SAFETY_BUDGET:
        return "terminal_budget_node"

    # 2. Check if LLM emitted tool calls
    messages = state.get("messages", [])
    last_message = messages[-1] if messages else None

    if last_message and hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tool_node"

    return "end"


def build_survey_agent_graph(llm: Any = None) -> Any:
    """Constructs the compiled LangGraph StateGraph."""
    workflow = StateGraph(AgentState)

    # Add Nodes
    workflow.add_node("router_node", router_node)
    workflow.add_node("agent_node", create_llm_node(llm))
    workflow.add_node("tool_node", tool_execution_node)
    workflow.add_node("terminal_budget_node", terminal_budget_node)

    # Add Edges
    workflow.add_edge(START, "router_node")

    # Conditional edge from router: either 'agent_node' or 'end'
    workflow.add_conditional_edges(
        "router_node",
        route_decision,
        {
            "agent_node": "agent_node",
            "end": END,
        },
    )

    # Conditional edge from agent_node: loop safety budget check, tool execution, or end
    workflow.add_conditional_edges(
        "agent_node",
        route_after_llm,
        {
            "terminal_budget_node": "terminal_budget_node",
            "tool_node": "tool_node",
            "end": END,
        },
    )

    # From tool_node, loop back to agent_node
    workflow.add_edge("tool_node", "agent_node")

    # From terminal_budget_node, transition to END
    workflow.add_edge("terminal_budget_node", END)

    return workflow.compile()
